#!/usr/bin/python
import re, sys
import os, subprocess
def matching(Trip, Code, line):
	for x in range(0, len(Trip)):
		if re.match( Code[x], line ):
			line = re.sub(Code[x], Trip[x], line)
			return line		

	return line
def find_related(pattern, pdb):
	pdbline = pdb.readline()
	print pdbline[17:20]
	if not pdbline:
		return 1

	return
os.system('cat '+sys.argv[1]+' | head -10 | tail -4 | fold -w 1 > tmp')
dsspf = open('tmp', 'r')
pdbf = open(sys.argv[2], 'r')
Triplets = [ 'ALA', 'ARG', 'ASN', 'ASP', 'CYS', 'GLN', 'GLU', 'GLY', 'HIS', 'ILE', 'LEU', 'LYS', 'MET', 'PHE', 'PRO', 'SER', 'THR', 'TRP', 'TYR', 'VAL' ]
Codes = [ 'A', 'R', 'N', 'D', 'C', 'Q', 'E', 'G', 'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V' ]
while (True):
	line = dsspf.readline()
	if not line: break
	line = matching(Triplets, Codes, line)
	find_related(line, pdbf)
	#print line.rstrip('\n')
os.system('rm tmp')
