#!/usr/bin/python
## Program for grouping dali aligned files and old but correct dssp files
## Notes:
##  Old structure files are in ../oldndssp 
##  Old seek files are in ../olddssp
##
import sys
import re
def reform(notdssp, dssp, outdssp, outnot):
        import os, subprocess
        lines = dssp.readlines()
        baltlist = []
	which = 0
	mode = 0
	for y in lines:
                read = notdssp.readline()
                if('>' in read):
			if which == 0:
				first = read[1:].rstrip('\n')
				outdssp.write(y)
				outnot.write(read)
			else:
				second = read[1:].rstrip('\n')
				f = open('fastas/'+first+'_'+second+'_dali_ali.fa', 'r')
				fasta_lines = f.readlines()
				for x in fasta_lines:
					if read == x: mode = 1
					elif read.rstrip('\n')+'_dssp\n' == x: mode = 2
					if mode == 1: outnot.write(x)
					elif mode == 2: outdssp.write(x)
				mode = 0
			which += 1	 
		else:
			if which == 1:
				outdssp.write(y)
				outnot.write(read)
			
	outnot.close()
	outdssp.close()	
					
class bcolors:
        FAIL = '\033[91m'
        BOLD = '\033[95m'
        BLUE = '\033[94m'
        GREEN = '\033[92m'
        YELLOW = '\033[93m'
        RESET = '\033[0m'
#   Atstovu atstovai
frdssp = open('../oldatst/atst.dssp', 'r')
frdnot = open('../oldatst/atst.notdssp', 'r')
fdssp = open('../atst/atst.notdssp', 'w')
fnot = open('../atst/atst.dssp', 'w')
reform(frdssp, frdnot, fdssp, fnot)

##   Grupes su atstovais
for x in range(1,16):
        frdssp = open('../olddssp/'+str(x), 'r')
        frdnot = open('../oldndssp/'+str(x), 'r')
	fnot = open('../dssp/'+str(x), 'w')
	fdssp = open('../notdssp/'+str(x), 'w')
        reform(frdssp, frdnot, fdssp, fnot)

