#!/bin/sh
var=0
python $1 > magic.txt
while [ "$var" = 0 ]
do
	sleep 2
	SMD=$(diff -H smth.txt magic.txt)
	python $1 > smth.txt
	if [ "$SMD" != "" ]
	then
		cat smth.txt
		python $1 > magic.txt
	fi
done

#	ENDLESS=$(python $1)
#	if [ "$ENDLESS" != "$MLESS" ]
#	then
#		MLESS=$(python $1)
#	fi
#	sleep 1
#done
