#!/bin/sh
# Usage ./mysh program
# loop for cahnging program's
# Show the different changed program output.
var=0
python $1 > magic.txt
while [ "$var" = 0 ]
do
	sleep 2
	SMD=$(diff smth.txt magic.txt)
	python $1 > smth.txt
	if [ "$SMD" != "" ]
	then
		cat smth.txt
		python $1 > magic.txt
	fi
done
