#!/usr/bin/python
import sys
AA = {'HOH': '-', 'ALA': 'A', 'ARG': 'R', 'ASN': 'N', 'ASP': 'D', 'CYS': 'C', 'GLN': 'Q', 'GLU': 'E', 'GLY': 'G', 'HIS': 'H', 'ILE': 'I', 'LEU': 'L', 'LYS': 'K', 'MET': 'M', 'PHE': 'F', 'PRO': 'P', 'SER': 'S', 'THR': 'T', 'TRP': 'W', 'TYR': 'Y', 'VAL': 'V'}
pdbf = open(sys.argv[1], 'r') 
fastaf = open('fa', 'w')
line = pdbf.readline()
while line:
	if line[13:15] == 'CA':
		Acid = line[17:20]
		try:
			fastaf.write(AA[Acid])
		except KeyError:
			print ''
	line = pdbf.readline()
