#!/usr/bin/python
import sys
import os
import subprocess
import re

if len(sys.argv) < 1:
	print 'Use ./pdb_to_dssp dssp_file'
	print "output is file dssp.new"
	exit()
fdssp = open(sys.argv[1], 'r')
lines = fdssp.readlines()
read = 0; fa_lines = ''; dssp_lines = ''; run = True

for line in lines:
	if read and not re.match('^>', line):
		dssp_lines += line.rstrip('\n')

	if re.match('>', line):
		read = 0

	if re.match('>1t6l_A', line):
		read = 1
	
os.system('./pdbtofast 11czd_C_1t6l_A_dali.pdb > 1czd_C_1t6l_A.fa')
fa = open('1czd_C_1t6l_A.fa', 'r')
while(run):
	line = fa.readline()
	if not line: run = False
	fa_lines += line.rstrip('\n')
fa = 0; ds = 0; run = True; stuck = 0
#fa_lines = fa_lines[:60]
#dssp_lines = dssp_lines[:60]

while run:
	if dssp_lines[ds] == '-':
		ds += 1
		sys.stdout.write('-')	
		stuck = 0

	elif fa_lines[fa] == dssp_lines[ds]:
		
		sys.stdout.write(dssp_lines[ds])
		fa += 1; ds += 1
		stuck = 0

	elif stuck > 15:
		ds += 1; fa -= 16		
		stuck = 0
	elif fa_lines[fa+1] == dssp_lines[ds+1] and fa_lines[fa+2] == dssp_lines[ds+2]:
		fa += 1
		ds += 1

	else:
		stuck += 1
		fa += 1	

	if ds+2 == len(dssp_lines) or fa+2 == len(fa_lines): 
		run = False

print "\n"

