#!/usr/bin/python
import sys
import os
import subprocess
import re
def fatopdb(struct, pdbf):
	fo = open(pdbf, 'r')
	fw = open('newpdb', 'w')
	lines = fo.readlines()
	cc = 0;
	#for x in struct:
	fw.write(lines[0])
	for line in lines:
		try:
			if (struct[cc]+1) < int(line[22:25]):
				cc += 1
		
			if cc == len(struct):
				fw.write(lines[-1])
				return
		
			if (struct[cc]+1) == int(line[22:25]):
				fw.write(line)
		except ValueError:
			print ''
		
	fw.write(lines[-1])
	return

if len(sys.argv) < 1:
	print 'Use ./pdb_to_dssp dssp_file'
	print "output is file dssp.new"
	exit()
fdssp = open(dssp, 'r')
dssp_lines = fdssp.readlines()
read = 0; fa_lines = ''; dssp_lines = ''; run = True
'''
for line in lines:
	if read and not re.match('^>', line):
		dssp_lines += line.rstrip('\n')

	if re.match('>', line):
		read = 0

	if re.match('>1t6l_A', line):
		read = 1
'''
pdbf = "../11czd_C_1t6l_A_dali.pdb"
structfile = sys.argv[1]
#fstruct = open(structfile[:-4]+"str",'r')
os.system('./pdb2f '+pdbf)
fa = open('../fastas/fa', 'r')
while(run):
	line = fa.readline()
	if not line: run = False
	fa_lines += line.rstrip('\n')
fa = 0; ds = 0; run = True; stuck = 0
struct = []

while run:
	
	if dssp_lines[ds] == '-':
		ds += 1
		sys.stdout.write('-')	
		stuck = 0

	elif fa_lines[fa] == dssp_lines[ds]:
		struct.append(fa)
		sys.stdout.write(dssp_lines[ds])
		fa += 1; ds += 1
		stuck = 0

	elif stuck > 15:
		ds += 1; fa -= 16		
		stuck = 0

	elif fa_lines[fa+1] == dssp_lines[ds+1] and fa_lines[fa+2] == dssp_lines[ds+2]:
		fa += 1; ds += 1
		#struct.append(fa-1)

	else:
		#struct.append(fa)
		stuck += 1
		fa += 1	

	if ds == len(dssp_lines) or fa == len(fa_lines): 
		run = False

print "\n"
print struct
fatopdb(struct, pdbf)
