#!/usr/bin/perl -w
#------------------------------------------------------------------------
#$Author: saulius $
#$Date: 1998/02/25 11:01:10 $ 
#$Header:
#$Locker: saulius $
#$Log: oligowt,v $
#Revision 1.1  1998/02/25 11:01:10  saulius
#Initial revision
#
#$Revision: 1.1 $
#$Source: /home/saulius/src/molwt/RCS/oligowt,v $
#$State: Exp $
#------------------------------------------------------------------------

# calculate amino acid composition from the polipeptide sequence

use strict;

my %amino_acids = ();

my $sequence = join( "", grep !/^\s*#/, <>);
$sequence =~ s/\s+//g;

my $acid;
foreach $acid (split("", $sequence)) {
    $amino_acids{$acid}++;
} 

for $acid ( sort keys %amino_acids) {
    printf "%s\t%d\n", $acid, $amino_acids{$acid};
}
