#!/bin/sh
#!perl -w # --*- Perl -*--
eval 'exec perl -x $0 ${1+"$@"}'
    if 0;
#-----------------------------------------------------------------------
#$Author: grazulis $
#$Date: 1999/10/11 10:11:43 $ 
#$Locker: grazulis $
#$Revision: 1.0 $
#$Source: $
#$State: Exp $
#------------------------------------------------------------------------
#*
# convert tha alignment file to .blc format
#**

use strict;
use Three2One;
use SOptions;
use SUsage;

#*USAGE:
#    align2blc a.align > a.blc
#**

print " $ARGV[0]\n";
print ">1 Name:\n";
print ">2 Name:\n";
print "* iteration 1\n";

while(<>) {
    my @line = split;
    print $line[1] !~ /\./ ? $Three2One::three_to_one{$line[1]} : ".";
    print $line[3] !~ /\./ ? $Three2One::three_to_one{$line[3]} : ".";
    print "\n";
}

print "*\n";
