#!/bin/sh

# remove the extension from the file name, if it exists
FILE_NAME=`echo $1 | sed -e 's/\.[^\./]*$//'`
FILE_EXTENSION=`echo $1 | awk -F. '{print $NF}'`
REMOVE_BLC="false"

convertMsf()
{
	msf2blc <<- eof-msf2blc
		$FILE_NAME.msf
		$FILE_NAME.blc
	eof-msf2blc
}

convertClus()
{
	clus2blc <<- eof-clus2blc 
		$FILE_NAME.clus
		$FILE_NAME.blc
	eof-clus2blc
}

case "$FILE_EXTENSION" in
	"msf"  ) convertMsf  ; REMOVE_BLC="true" ;;
	"clus" ) convertClus ; REMOVE_BLC="true" ;;
	"blc"  ) ;;
	"$FILE_EXTENSION" ) 
	   echo Hardly I know file type "$FILE_EXTENSION"... 
	   exit
	   ;;
esac

NR_OF_SEQUENCES=`awk 'BEGIN{seqNr=0}/>/{seqNr++}/\*/{print seqNr; exit}' $FILE_NAME.blc`
NR_OF_RESIDUES=`awk \
   'BEGIN{start=0}/\*/{start=1-start;}!/\*/{if(start) print}' $FILE_NAME.blc | wc -l`

cat <<- eof-cat > alscript.$$.inp
	BLOCK_FILE $FILE_NAME.blc
	OUTPUT_FILE $FILE_NAME.ps
	LANDSCAPE
	POINTSIZE 12
	# 
	DEFINE_FONT 0 Helvetica DEFAULT
	# This means call Helvetica-Oblique at 70% of the default point size, font 1
	DEFINE_FONT 1 Helvetica-Oblique REL 0.70
	DEFINE_FONT 2 Helvetica-Bold DEFAULT
	DEFINE_FONT 5 Symbol REL 1.2
	DEFINE_FONT 6 Helvetica REL 0.7
	#
	# Colour definitions: DEFINE_COLOUR <NR> <R> <G> <B>
	# 
	# red
	DEFINE_COLOUR 1 1 0 0
	# yellow
	DEFINE_COLOUR 2 1 1 0
	# blue
	DEFINE_COLOUR 3 0 0 0.3
	# green
	DEFINE_COLOUR 4 0 1 0
	# magic  
	DEFINE_COLOUR 5 0 1 0
	DEFINE_COLOUR 6 0.58 0.58 0.58
	DEFINE_COLOUR 7 0.75 0.75 0.75
	DEFINE_COLOUR 8 0 0   0
	DEFINE_COLOUR 9 0.40 0.40 0.40
	DEFINE_COLOUR 10 0 1 0
	DEFINE_COLOUR 11 0.95 0.95 0.95 
	DEFINE_COLOUR 12 1 1 1
	DEFINE_COLOUR 13 1 0 1
	DEFINE_COLOUR 16 0.1 0.6 1.0
	DEFINE_COLOUR 98 1 1 1
	#
	#BACKGROUND_COLOUR 11
	#
        # NO_NUMBERS
	ADD_SEQ 2 1
        SETUP
	SUB_CHARS 1 3 ${NR_OF_RESIDUES} 3 SPACE x
	CCOL_CHARS x 1 3 ${NR_OF_RESIDUES} 3 98
        HELIX 10 3 20
	# Calcuate conservation values for the complete alignment.  Conservation
	# values range from 0-10 where 10 is an identity.  Values above 5 show
	# increasing similarities in physico-chemical properties.  Having calculated
	# conservation values, we can then colour the plot to highlight conserved
	# positions.
	#
	CALCONS 1 1 $NR_OF_RESIDUES $NR_OF_SEQUENCES
	#
	SUB_CHARS ALL SPACE .
	mask SETUP
	mask ILLEGAL ".-_"
	#
	# masks ALL columns for which the conservation is > 7.
	mask CONSERVATION ALL 6
	mask CCOL ALL 3
	mask RESET
	#
	mask CONSERVATION ALL 7
	mask BOX  ALL
	mask CCOL ALL 100
	mask SCOL ALL 2
	mask RESET
	#
	# identities:
	mask ILLEGAL ".-_"
	mask CONSERVATION ALL 10
	# mask ID   ALL  $NR_OF_SEQUENCES
	mask BOX  ALL 
	mask CCOL ALL 98
	mask SCOL ALL  1
	mask FONT ALL  2
	mask RESET
	#SUB_CHARS ALL . SPACE
eof-cat

if [ "$2" != "" -a -f "$2" ]
then 
   cat $2 >> alscript.$$.inp
fi

alscript <<- eof-alscript
	alscript.$$.inp	
eof-alscript

rm -f alscript.$$.inp

if [ $REMOVE_BLC = "true" ]
then
   rm -f $FILE_NAME.blc
fi
