#!/usr/bin/expect --

spawn telnet assel

expect "ogin:"    { send   "grazulis\r" }
expect "assword:" { send   "juru\$pleksne\r" }
expect "TERM = (unknown)" { send "\r" }
expect ">"        { send "linterm\r" }

interact
