#!/bin/bash
#------------------------------------------------------------------------------
#$Author: andrius $
#$Date: 2014-06-02 10:48:13 +0300 (Pr, 02 Bir 2014) $ 
#$Revision: 443 $
#$URL: svn://saulius-grazulis.lt/scripts/buffer $
#------------------------------------------------------------------------------
#*
#   Saves contents of STDIN to temp file and launches command, specified
#   by command line parameters, appending the name of temp file as the
#   last command line parameter.
#**

EXT=tmp
TMPFILE=/tmp/tmp-$(basename $0)-$$.${EXT}

cat /dev/stdin > ${TMPFILE}
$* ${TMPFILE}
sleep 2
rm ${TMPFILE}
