#!/bin/sh

extension()       
{ 
   echo $1 | awk -F. '{print $NF}'
}

removeExtension() 
{ 
   basename $1 | sed -e 's/\.[^\./]*$//'
}

set +u

READ_MOL=$0.molecules
READ_SCRIPTS=$0.scripts
LABELS=$0.labels

rm -f $READ_MOL $READ_SCRIPTS $LABELS
touch $READ_MOL $READ_SCRIPTS $LABELS

i=1
s=1
while [ "$1" != "" ]
do
   case "`extension $1`" in
      "ps")  OUTPUT_PS=$1 ;;
      "pdb")
             echo "read mol$i \"$1\";" >> $READ_MOL
             echo "label 5.0 "`echo "scale=2; -($i/0.5+35.0)" | bc`" 0.0 \"$1\";" >> $LABELS
             i=`expr $i + 1`
             test -z "$OUTPUT_PS" && OUTPUT_PS=`removeExtension $1`.ps ;;
       *)
             cat $1 >> $READ_SCRIPTS
             s=`expr $s + 1` ;;
   esac
   shift
done

cat $LABELS

set +e

molscript > $OUTPUT_PS <<- eof-molscript
plot noframe

  @$READ_MOL
  @$READ_SCRIPTS

  set linecolour black;
  trace molecule mol1;
  `sed -n '1,1 p' $LABELS`

  set linecolour red;
  trace molecule mol2;
  `sed -n '2,2 p' $LABELS`

  set linecolour blue;
  trace molecule mol3;
  `sed -n '3,3 p' $LABELS`

  set linecolour green;
  trace molecule mol4;
  `sed -n '4,4 p' $LABELS`

  set linecolour purple;
  trace molecule mol5;
  `sed -n '5,5 p' $LABELS`
  
end_plot
eof-molscript

rm -f $READ_MOL $READ_SCRIPTS $LABELS
