#!/usr/bin/awk -f

BEGIN{
   y1 = "";
   y2 = "";
}

{
   if( y1 == "" ) {
      y1 = $2
      x1 = $1
   } else {
      if( y2 == "" ) {
         y2 = $2
         x2 = $1
         print x1, (y1-y2)/(x1-x2)
      } else {
         print x2, ($2 - y1) / ($1 - x1);
         y1 = y2; y2 = $2;
         x1 = x2; x2 = $1;
      }
   }
}

END {
    print x2, (y1-y2)/(x1-x2)
}