#!/usr/bin/perl -w
#------------------------------------------------------------------------
#$Author:$
#$Date:$ 
#$Header:
#$Locker:$
#$Log:$
#$Revision:$
#$Source:$
#$State:$
#------------------------------------------------------------------------
#*
# Make table of contents (toc) from the tar tape listing
# (produced with 'tar tv' command)
#**

use strict;

while(<>) {
    print if(/^d/);
}
