#!/bin/sh

set -u

NEW_STATUS=""
OLD_STATUS=""

while true
do
  NEW_STATUS="`edg-job-status $1`"
  if [ "$NEW_STATUS" != "$OLD_STATUS" ]
  then
      printf "%s\n" "$NEW_STATUS"
      if echo "$NEW_STATUS" | grep "Current Status:     Done (Success)" \
	  >& /dev/null
      then
	  echo "$0: Job finished."
	  break
      fi
  else
      echo -n "."
  fi
  OLD_STATUS="$NEW_STATUS"
  sleep 5
done
