#!/usr/ucb/sh

while [ "$1" != "" ]
do

# remove extension from the file name:
FILE_NAME=`echo $1 | sed -e 's/\.[^\./]*$//'`

echo $1

# extract sequences from the FASTA file

grep '^[a-zA-Z01-9_]*:[^ ]*$' $1 | awk -F: '{print substr($2,1,6)}' > $FILE_NAME.$$.patterns

PATTERN_NR=`wc -l < $FILE_NAME.$$.patterns`

COUNT=1

while [ $COUNT -lt $PATTERN_NR ]
do
   CURRENT_PATTERN=`sed -n "$COUNT,$COUNT p" $FILE_NAME.$$.patterns`
   
   awk "BEGIN{printed=0}\
        /overlap/{OL=\$0}\
        /^$CURRENT_PATTERN *[-A-Z]* *\$/\
            { \
               if(printed==0) { \
                  print \"\.\.\"; \
                  printed=1; \
                  } \
               print \$2; \
            }" $1  > $FILE_NAME.$CURRENT_PATTERN.seq
   COUNT=`expr $COUNT + 1`
#        /^[a-zA-Z01-9_]*:$CURRENT_PATTERN.*\$/\
#                  print OL; \
done

rm -f $FILE_NAME.$$.patterns

shift
done

