#!/bin/sh

# Find all PDF files and assist renaming them according to our format

find ${1+"$@"} \
    -type f \
    -name \*.pdf \
    -print0 \
    -o \
    -name \*.od? \
    -print0 \
| grep -z -vE '[0-9]{4}_[A-Za-zА-Яа-я][-A-Za-zА-Яа-я]*_?.*\.(pdf|od.)$' \
| xargs -0 -i sh -c 'rename-papers "{}" < /dev/tty'
