#! /bin/sh
#!perl -w # --*- Perl -*--
eval 'exec perl -x $0 ${1+"$@"}'
    if 0;
#------------------------------------------------------------------------------
#$Author: saulius $
#$Date: 2001/06/12 14:11:27 $ 
#$Locker: saulius $
#$Revision: 1.2 $
#$Source: /home/saulius/src/data-processing/RCS/fit,v $
#$State: Exp $
#------------------------------------------------------------------------------
#*
#  Find linear least-squares fit to data
#**

while(<>){
  if( ! /^ *#/ ){
     ( $x[$#x + 1], $y[$#y + 1] ) = split(' ');
  }
}

$mx = $my = 0.0;

for( $i=0; $i <= $#x; $i++) {
   $mx += $x[$i];
   $my += $y[$i];
}

$mx /= ($#x + 1);
$my /= ($#y + 1);

$a = $d = 0.0;
for( $i=0; $i <= $#x; $i++) {
   $a += ($x[$i] - $mx) * ($y[$i] - $my);
   $d += ($x[$i] - $mx) * ($x[$i] - $mx);
}

$a /= $d;
$b = $my - $a * $mx;
printf "%g * x + %g\n", $a, $b; 
