#!/bin/sh
#------------------------------------------------------------------------------
#$Author: saulius $
#$Date: 2015-03-01 15:23:50 +0200 (Sk, 01 Kov 2015) $
#$Revision: 498 $
#$URL: svn://saulius-grazulis.lt/scripts/genbibtex $
#------------------------------------------------------------------------------
#*
#  USAGE:
#      $0 [directory list]
#
#  Generate BiBTeX bibliography from the directory of the PDF files,
#  where each file is named in a regular way: Year_Author_Page*.pdf
#  or Year-Author-Page*.pdf
#**

set -ue

ID='$Id: genbibtex 498 2015-03-01 13:23:50Z saulius $'

DIRS=""

#** OPTIONS:
#**  --help                   print short help message (this message) and exit
while [ $# -gt 0 ]
do
  case $1 in
      --help|--hel|--he|--h)
            awk '/#\*/,/#\*\*/ {
                    sub("^ *#[*]?[*]?", ""); \
                    gsub("\\$0","'$(basename $0)'"); \
                    print $0
                }' $0
	    exit
	    ;;      
      -*) echo "`basename $0`: unknown option $1" >&2 ; exit 1 ;;
      *)  DIRS="$DIRS '$1'" ;;
    esac
    shift
done

## echo ${DIRS}
eval set -- "${DIRS}"

DATE=$(date +%Y.%m.%d)

find ${1+"$@"} \
    -name .svn -prune \
    -o \
    -iname '[0-9X][0-9X][0-9X][0-9X]_[a-zа-я]*_[0-9a-zа-я]*.pdf' -print0 \
    -o \
    -iname '[0-9X][0-9X][0-9X][0-9X]_[a-zа-я]*.pdf' -print0 \
    -o \
    -iname '[0-9X][0-9X][0-9X][0-9X]_[a-zа-я]*_[0-9a-zа-я]*.ps*' -print0 \
    -o \
    -iname '[0-9X][0-9X][0-9X][0-9X]_[a-zа-я]*.ps*' -print0 \
    -o \
    -iname '[0-9X][0-9X][0-9X][0-9X]_[a-zа-я]*_[0-9a-zа-я]*.od?' -print0 \
    -o \
    -iname '[0-9X][0-9X][0-9X][0-9X]_[a-zа-я]*.od?' -print0 \
| xargs -0 \
    mkbibentry
