#!/bin/csh
if( $1 == "" ) then
  set SOLUTIONS="solutions/*"
  echo "$SOLUTIONS"
else
  set SOLUTIONS=$1
endif 

set OLD_DIRECTORY=`pwd` 
foreach i ( `echo $SOLUTIONS` )
#  echo $i
  cd $i
  echo '----------------------------------------------------------------------'
  set SOLUTION_NAME=`pwd`
  echo $SOLUTION_NAME:h"/" 
  echo $SOLUTION_NAME:t"/"
  awk '/PDB |MTZ /{ print $5 }' auto_amore.log
  awk '/Resolution /{ print toupper($1) "\t", $6, $7 }' auto_amore.log
  awk '/SPHERE/{ print $1 "\t\t", $2, $3 }' auto_amore.log | uniq
  awk '/RF unit /{ print $1, $2, $3 "\t", $5, $6, $7 }' auto_amore.log
  grep SOLUT *packing.okay | head -5 
  cd $OLD_DIRECTORY
end

 
