#!/bin/sh

CD_SIZE="$1"
shift

if [ $# -gt 0 ]
then
    list_cmd='du -ks ${1+"$@"}'
else
    list_cmd=cat
fi

eval ${list_cmd} \
| awk '{
	if( s + $1 > '$CD_SIZE' ) {
	    print "cd",++n,"===";
	    s=0
	}
	s+=$1;
	print s, $0
       }
       END {
	print "cd",++n,"==="
       }'
