#!/usr/bin/perl -w
#-----------------------------------------------------------------------
#$Author: grazulis $
#$Date: 1998/01/17 18:33:44 $
#$Header:
#$Locker: grazulis $
#$Revision: 1.1 $
#$Source: /kaefer/u05/grazulis/src/CCE/perl-modules/RCS/imagerange,v $
#$State: Exp $
#-----------------------------------------------------------------------
# find runs of continuos images
#-----------------------------------------------------------------------

use strict;
use Mar;
use ImageRange;

my $Id = '$Id: imagerange,v 1.1 1998/01/17 18:33:44 grazulis Exp grazulis $ ';

my @headers = Mar::readHashHeaders( @ARGV );
my @ranges  = ImageRange::findImageRanges( \@headers );

## foreach (@headers) {
##     print "$$_{name}\n";
## }

my $range;
foreach $range (@ranges) {
    my $delta_phi  = $$range[0]{delta_phi};
    my $name_start = $$range[0]{name};
    my $name_end   = $$range[-1]{name};
    my $phi_start  = $$range[0]{phi_end} - $delta_phi;
    my $phi_end    = $$range[-1]{phi_end} - $delta_phi;
    print "range $name_start to $name_end phi $phi_start to $phi_end (delta = $delta_phi)\n";
}
