#!/bin/sh

awk '!/helix|strand|coil|turn|end_plot/{if ( $1 == "plot" ) print "plot noframe"; else print $0; }' $1

awk '{ if ( $1 == "helix" ) print $0; }' $1 | sort -n +3
echo " "
cat $1 | awk '{ if ( $1 == "strand" ) print $0; }' | sort -n +3
echo " "
cat $1 | awk '{ if ( $1 == "coil" ) print $0; }' | sort -n +3 
echo " "
cat $1 | awk '{ if ( $1 == "turn" ) print $0; }' | sort -n +3

echo ""
echo "end_plot"
