#!/bin/sh

set -ue

/bin/ls \
| a2ps \
    -o- \
    -1 \
    -R \
    -f7.7 \
    --columns=2 \
    --rows=2 \
    --borders=no \
    --no-header \
    --medium=a5 \
${1+"$@"}

#    --columns=4 \
#    --rows=2 \
