#!/usr/bin/perl
# Mirror the string - print it in reversed order;
# e.g. "atc" gives you "cta"
# the string is give as command line argument or read from
# the STDIN

if($#ARGV < 0) {
  while(<>) {
     &mirror($_);
     print "\n";
  }
}
else {
  while($#ARGV >= 0) {
     &mirror($ARGV[0]); 
     print "\n";
     shift;
  }
}

sub mirror
{
   local($string) = @_;
   for $i (1 .. length($string)) {
       print substr($string, -$i, 1);
   }
}
