#!/bin/sh
#------------------------------------------------------------------------------
#$Author: saulius $
#$Date: 2014-12-16 12:25:02 +0200 (An, 16 Grd 2014) $
#$Revision: 479 $
#$URL: svn://saulius-grazulis.lt/scripts/mkmd5sums $
#------------------------------------------------------------------------------

set -ue

BASENAME="`basename $0`"
EXECUTABLE="`echo $BASENAME | sed -e 's/^mk\(.*\)s$/\1/'`"

if [ ${EXECUTABLE} = ${BASENAME} ]
then
    EXECUTABLE=md5sum
fi

SUMS=${EXECUTABLE}.dat

find ${1+"$@"} -type f -print0 \
| xargs -n1 -0 ${EXECUTABLE} \
| grep -v "  ./${SUMS}\$" \
| grep -v "  ./md5sum.dat\$" \
| grep -v "  ./sha[0-9][0-9]*sum.dat\$" \
| sort -k 2 \
> ${SUMS}
