#! /bin/sh
#------------------------------------------------------------------------------
#$Author: saulius $
#$Date: 2003/02/05 08:58:47 $ 
#$Locker: saulius $
#$Revision: 1.2 $
#$Source: /home/saulius/src/scripts/RCS/mkomac,v $
#$State: Exp $
#------------------------------------------------------------------------------
#*
#   Correct O macro (script) file, counting lines and each
#   line's length, and putting these numbers into the file header
#**

set -ue
## set -x

awk 'BEGIN { n = 0; maxlen = 0 }
     $2 ~ /^[Tt]$/ { if( !name ) { name = $1; next }}
     { 
         script[n] = $0;
         n++;
         if( maxlen < length )
             maxlen = length;
     }
     END {
         printf "%-26s%-9s%3d%9s%2d\n", name, "T", n, "", maxlen+1;
         for( i = 0; i < n; i++ ) { 
             print script[i];
         }
     }' "${@}"
