#! /bin/sh
#!perl -w # --*- Perl -*--
eval 'exec perl -x $0 ${1+"$@"}'
    if 0;
#------------------------------------------------------------------------------
#$Author: saulius $
#$Date: 2014-12-06 20:49:01 +0200 (Št, 06 Grd 2014) $ 
#$Revision: 478 $
#$URL: svn://saulius-grazulis.lt/scripts/mrk2bibtex $
#------------------------------------------------------------------------------
#*
#  Convert my MRK bibliography files to the BibTeX format.
#**

use strict;

$/ = ""; # read input paragraph-wise

my @keys = qw( 
    title journal year volume number month pages
    doi url file
    date note keywords
);

my %bibkeys;

while(<>) {
    my %bibtex_entry;
    if( /<authors.*?>(.*?)<\/authors>/ ) {
        my $authors = $1;
        my @authors = map {s/^\s+|\s+$//g; $_} split( ";", $authors );
        $authors =~ s/;/ and /g;
        $authors =~ s/\s+/ /g;
        $bibtex_entry{author} = $authors;
        my $first_author_surname;
        if( $authors[0] =~ /,/ ) {
            my @first_author = split( ',\s*', $authors[0] );
            $first_author_surname = $first_author[0];
        } else {
            my @first_author = split( ' ', $authors[0] );
            $first_author_surname = $first_author[-1];
        }
        $bibtex_entry{first_author} = $authors[0];
        $bibtex_entry{first_author_surname} = $first_author_surname;
    }

    for my $key (@keys) {
        use Switch;
        my $tag;
        switch( $key ) {
            case "number" { $tag = "issue" }
            else { $tag = $key }
        }
        if( /<$tag>(.*?)<\/$tag>/ ) {
            $bibtex_entry{$key} = $1;
        }
    }

    if( %bibtex_entry ) {
        no warnings;
        my $bibkey = $bibtex_entry{first_author_surname} . $bibtex_entry{year};
        $bibkey =~ s/\s//g;
        my $final_bibkey = $bibkey;
        my $suffix = "a";
        while( defined $bibkeys{$final_bibkey} ) {
            $final_bibkey = $bibkey . $suffix;
            if( $suffix == "z" ) {
                $bibkey .= "a";
                $suffix = "a";
            } else {
                $suffix = chr(ord($suffix) + 1);
            }
        }
        $bibkeys{$final_bibkey} = $final_bibkey;
        print '@ARTICLE{', $final_bibkey, ",\n";
        use warnings;
        for my $key (("author", @keys)) {
            print "    $key = {$bibtex_entry{$key}},\n" if exists $bibtex_entry{$key};
        }
        print "}\n\n";
    }
}
