#!/bin/sh
#
if [ $# = 0 ]
then
    echo "usage: $0 -option STDIN"
    echo "New version of ovid2tex: option required"
    echo " "
    echo "-m: Data from MEDLINE database"
    echo "-b: Data from BIOSYS database"
    exit
fi

if [ "${1}" = "-m" ]
then
    OVID2TEX=$HOME/bin/ovid2tex_medline.awk
    cat -  | awk -f ${OVID2TEX} | \
        sed -e 's/\&/\\\&/g' -e 's/%/\\%/g'
else
     OVID2TEX=$HOME/bin/ovid2tex_biosys.awk
     cat - | sed 's/^<.*/Registry /g' | awk -f ${OVID2TEX} | \
	sed -e 's/\&/\\\&/g' -e 's/%/\\%/g'
fi


exit
#

