#! /bin/sh
#!perl -w # --*- Perl -*--
eval 'exec perl -x $0 ${1+"$@"}'
    if 0;
#------------------------------------------------------------------------------
#$Author:$
#$Date:$ 
#$Locker:$
#$Revision:$
#$Source:$
#$State:$
#------------------------------------------------------------------------------
#*
#  Generate pronoucable (pseudo-)random words
#**

use strict;

my $seed;
my $openssl = `bash -c 'type -p openssl' 2> /dev/null`;

$openssl =~ s/\s*$//g;

if( $openssl ) {
    ## print "$openssl rand 4\n";
    $seed = unpack( "I", `$openssl rand 4` );
} else {
    $seed = time();
}

srand( $seed );

my @consonant = (
    "b",
    "c",
    "d",
    "f",
    "g",
    "h",
    "j",
    "k",
    "l",
    "m",
    "n",
    "p",
    "q",
    "r",
    "s",
    "t",
    "v",
    "w",
    "x",
    "z",
    ""
);

my @wovel = (
    "a",
    "e",
    "i",
    "o",
    "u",
    "y",
);

my @punctuation = (
   "!",
   "@",
   "#",
   "\$",
   "%",
   "^",
   "&",
   "*",
   "-",
   "+",
   ".",
   ",",
   "/",
   "?",
   ";",
   "'",
   ":",
   "\"",
);

my $word1 = "";
my $word2 = "";

my $syllables1 = 2 + rand(3);
my $syllables2 = 2 + rand(3);

for( 1..$syllables1 ) {
    $word1 .= $consonant[int(rand(int(@consonant)))];
    $word1 .= $wovel[int(rand(int(@wovel)))];
}

for( 1..$syllables2 ) {
    $word2 .= $consonant[int(rand(int(@consonant)))];
    $word2 .= $wovel[int(rand(int(@wovel)))];
}


my $pass = $word1 . $punctuation[int(rand(int(@punctuation)))] . $word2;

print $pass, "\n";
