#!/usr/ucb/csh

cat << eof > plotchi.gnu.$$
  set data style lines
  plot  '<grep "spots refined" $1' using 6,\
	'<grep "spots refined" $1' using 8,\
	1.4
  pause -1
eof

gnuplot plotchi.gnu.$$

rm -f plotchi.gnu.$$
