#!/bin/csh -f

set OSARCH   = `uname -s | gawk '{print tolower($0)}'`

switch ( $OSARCH )
    case irix*:
	hinv | gawk '/CPU/{p=tolower($3);sub(".00$", "k", p);print p}'
	breaksw
    default:
	uname -m
	breaksw
endsw
