#!/bin/sh

awk -F/ \
'  BEGIN {
      length1 = split(ARGV[1], path1);
      length2 = split(ARGV[2], path2);
      min = length1 < length2 ? length1 : length2;
      for( i = 2; i <= min; i++ ) {
          if( path1[i] != path2[i] )
              break;
      }
      ORS = "/";
      for( l = i; l <= length2; l++ ) print "..";
      for( l = i; l <= length1; l++ ) print path1[l];
      printf "\n";
   }
' $1 $2
