#!/bin/sh

if [ $# -gt 0 ]
then
    INTERFACE=$1
else
    INTERFACE=eth0
fi

set -x

sudo route del default
sudo route add default gw dslmodem
sudo route add -host dslmodem ${INTERFACE}
sudo route add -host erelis ${INTERFACE}
sudo vpnd
sleep 10
sudo route add -net 192.168.61.0/24 gw 10.1.1.1
