#!/bin/sh

gnuplot <<EOF
        set term post colo
        set data style lines
	set grid
        set xlabel "steps of refinement"
        set ylabel "Rfactor"
        set title "Refinement of $1 (`date`)"
        plot "<gawk '/XTAREXPR.*WORKING SET/{print \$NF}' $1" title "R",\
             "<gawk '/XTAREXPR.*TEST SET/{print \$NF}' $1" title "Rfree" \
              with lines 3 1
EOF
