#!/bin/sh

TICS=""
STEPNR=0

for file in $*
do
    wcount=`gawk '/XTAREXPR.*WORKING SET.*monitor= *[.0-9]+/{print \$NF}' $file | wc -l`

    TIC_PREV=$STEPNR
    STEPNR=`expr $STEPNR + $wcount`
    TIC_NOW=`expr $STEPNR - 1`
    TIC_HALF=`expr \( $TIC_PREV + $TIC_NOW \) / 2`

    test -n "$TICS" && TICS="$TICS, "
    basename=`basename "$file" .log | sed -e 's/minimise/m/g' -e 's/brefine/b/g'`
    spaces=`echo $basename | sed -e 's/./   /g'`
    TICS="$TICS'$basename$spaces' $TIC_NOW"
done

TMP_FILE="$tmp/tmp-all-$$.log"

cat $* > $TMP_FILE

gnuplot <<EOF
        set term post colo
        set data style lines
        set xlabel "Runs of refinement"
        set ylabel "Rfactor"
	set grid
        set title "CNS refinement `date|sed -e 's/\"//g'`"
	set xtics ( $TICS )
        plot "<gawk '/XTAREXPR.*WORKING SET.*monitor= *[.0-9]+/{print \$NF}' $TMP_FILE" title "R",\
             "<gawk '/XTAREXPR.*TEST SET.*monitor= *[.0-9]+/{print \$NF}' $TMP_FILE" title "Rfree" \
              with lines 3 1
EOF

rm -f $TMP_FILE
