#!/bin/sh

awk -v window=$1 "
{
   if(FNR<window)
      for(i=0;i<window;i++) { 
         x[i] = \$1;
         crude[i] = \$2;
         if(i<int(window/2))
            print \$1, "\t" \$2;
         getline;
      }
   else {
      average=crude[0];
      for(i=1;i<window;i++) {
         average += crude[i];
         crude[i-1] = crude[i];
      }   
      print x[int(window/2)], "\t" average / window;
      for(i=1;i<window;i++) 
         x[i-1] = x[i];
      x[window-1] = \$1;
      crude[window-1] = \$2;
   }   
}

END {
   for(i=int(window/2);i<window;i++) {
      print x[i], "\t" crude[i]
   }
}" $2
