#! /bin/sh
#------------------------------------------------------------------------------
#$Author: saulius $
#$Date: 2005/03/25 07:24:01 $ 
#$Locker: saulius $
#$Revision: 1.4 $
#$Source: /home/saulius/src/sort-sources/RCS/sort-sources,v $
#$State: Exp $
#------------------------------------------------------------------------------
#*
#   Sort source tarballs into separate directories, each package and version
#   automatically moved into a separate subdirectory.
#**

set -ue

SIG_LIST=".asc .sig .sign .md5 .md5sum"

EXT_LIST=".tar.gz .tar.bz2 .tar.Z .tar .zip .tgz .tbz2 .bz2 .jar \
.gz .Z .rpm .deb .exe .md5 -md5.sum .ppc.dmg .dmg .spec .patch .bin .iso .torrent"

for ext in $EXT_LIST
do
  for sig in "" $SIG_LIST
    do
    EXT=${ext}${sig}
    if [ "`echo *${EXT}`" != "*${EXT}" ]
	then 
	for i in *${EXT}
	  do
	  VField="`basename $i ${EXT} | awk -F- '{for(i=1;i<=NF;i++)if(match($i,"^[0-9.]+")!=0)break}END{print i}'`"
	  P=`basename $i ${EXT} | awk -F- "{for(i=1;i<$VField;i++){if(!s)s=\\$i; else s=s\"-\"\\$i}}END{print s}"`
	  V=`basename $i ${EXT} | awk -F- "{print \\$($VField)}" | sed 's/[^0-9]*\$//g'`
	  if [ -z "$V" ]
	    then
	      D=$P
	    else
	      D=$P-$V
	  fi
	  mkdir -p $D
	  mv -v $i $D/
	done
    fi
  done
done
