#!/bin/bash
#------------------------------------------------------------------------------
#$Author: saulius $
#$Date: 2013-03-02 17:14:26 +0200 (Št, 02 Kov 2013) $
#$Revision: 379 $
#$URL: svn://saulius-grazulis.lt/scripts/svn-dir-text-time $
#------------------------------------------------------------------------------

SCRIPT=false
FORCE=false

FILES=""

while [ $# -gt 0 ]
do
    case "$1" in
        -f|--force|--forc|--for|--fo|--f)
            FORCE=true
            ;;
        -f-|--no-force|--no-forc|--no-for|--no-fo|--no-f)
            FORCE=false
            ;;
        --script|--scrip|--scri|--scr|--sc|--s)
            SCRIPT=true
	    ;;
        --run|--ru|--r)
            SCRIPT=false
	    ;;
        -*) echo "$0: unknown option '$1'" >&2
            exit 1
	    ;;
        *)  FILES="'$1' ${FILES}"
    esac
    shift
done

if [ -z "${FILES}" ]
then
    FILES="."
fi

eval set -- "${FILES}"

for file
do

set -e

if [ "$FORCE" = true ] || svn proplist "$file" | grep -q svn:text-time
then

    ## echo ""
    ## echo == $file ==

    svn_time=`svn proplist -v "$file" | awk '/svn:text-time/{print $3}'`
    ls_longtime=$(
	export TZ=UTC
	ls -ld --time-style="+%Y-%m-%dT%H:%M:%S" "$file" | awk '{print $6}'
    )
    ls_microseconds=$(
	export TZ=UTC
	ls -ld --time-style="+%N" "$file" | awk '{printf "%06d\n", $6/1000}'
    )
    ls_time="${ls_longtime}.${ls_microseconds}Z"

    ## echo == $ls_time ==
    ## echo == $svn_time ==

    if [ "${ls_time}" != "${svn_time}" ]
    then
        cmd1="svn propset svn:text-time \"${ls_time}\" \"$file\""
        cmd2="svn proplist -v \"$file\""
        if [ "$SCRIPT" = false ]
        then
            eval $cmd1
            eval $cmd2
	else
            echo $cmd1
            echo $cmd2
        fi
        ## echo "text-time \"${ls_time}\""
        ## echo "replaces  \"${svn_time}\" on \"$file\""
        ## echo ""
    fi
fi

done

test $SCRIPT = true && echo "*** files not modified"
