#!/bin/bash
#------------------------------------------------------------------------------
#$Author: saulius $
#$Date: 2013-03-02 17:14:26 +0200 (Št, 02 Kov 2013) $
#$Revision: 379 $
#$URL: svn://saulius-grazulis.lt/scripts/svn-touch-text-time $
#------------------------------------------------------------------------------

SCRIPT=false
FORCE=false
EMPTY=false
VERBOSE=false

FILES=""

while [ $# -gt 0 ]
do
    case "$1" in
        -v|--verbose|--verbos|--verbo|--verb|--ver|--ve|--v)
            VERBOSE=true
            ;;
        -v-|--not-verbose|--not-verbos|--not-verbo|--not-verb|--not-ver|\
        --not-ve|--not-v|\
        --no-verbose|--no-verbos|--no-verbo|--no-verb|--no-ver|\
        --no-ve|--no-v)
            VERBOSE=false
            ;;
        --script|--scrip|--scri|--scr|--sc|--s)
            SCRIPT=true
	    ;;
        --run|--ru|--r)
            SCRIPT=false
	    ;;
        -*) echo "$0: unknown option '$1'" >&2
            exit 1
	    ;;
        *)  FILES="'$1' ${FILES}"
    esac
    shift
done

if [ -z "${FILES}" ]
then
    FILES="."
fi

eval set -- "${FILES}"

find "$@" -name .svn -prune -o \
    -type f \
    -exec bash -c \
'
set -e
file="{}"

svn_time=`svn proplist -v "$file" \
| awk "/svn:text-time/{getline; print \\\$1}" \
| sed -e "s/Z\\\$//; s/T/ /"`

if [ -n "${svn_time}" ]
then
    CMD="TZ=UTC touch --date=\"${svn_time}\" \"${file}\""

    test '${SCRIPT}' = true -o '${VERBOSE}' = true && echo ${CMD}
    test '${SCRIPT}' = false && eval ${CMD}
fi
' \;

test $SCRIPT = true && echo "*** tree not modified"
