#!/usr/bin/perl -w

use strict;

my @start = @ARGV[0,1,2];
my @n     = @ARGV[3,4,5];

$\ = "\n";
$, = "\t";

my $delta = 1.0;
my $i;
for $i (0..10) {
    my @pt = (
	      $start[0] + $i * $delta * $n[0],
	      $start[1] + $i * $delta * $n[1],
	      $start[2] + $i * $delta * $n[2],
	      );
    print @pt;
}
