#!/usr/bin/perl -w

use strict;

my @v1 = @ARGV[0,1,2];
my @v2 = @ARGV[3,4,5];

$\ = "\n";
$, = "\t";

my @n = map {$v2[$_] - $v1[$_]} (0,1,2);

my $nlen = sqrt( $n[0]**2 + $n[1]**2 + $n[2]**2 );

@n = map {$_/$nlen} @n;

my $delta = 1.0;
my $i = 0;
while( $i <= $nlen ) {
    my @pt = (
	      $v1[0] + $i * $delta * $n[0],
	      $v1[1] + $i * $delta * $n[1],
	      $v1[2] + $i * $delta * $n[2],
	      );
    print @pt;
    $i += $delta;
}
