#!/bin/sh


if grep -q "WORKING SET" $1
then
cat > gnuplot.inp << eof-cat1
	set term post colo
	set data style lines
	set xlabel "steps of refinement"
	set ylabel "Rfactor"
	set title "Refinement of $1 (`date`)"
	plot "<awk '/TRRESI.*WORKING SET/{print \$NF}' $1" title "R",\
	     "<awk '/TRRESI.*TEST SET/{print \$NF}' $1" title "Rfree" with lines 3 1
eof-cat1
else
cat > gnuplot.inp << eof-cat2
	set term post colo
	set data style lines
	set title "Refinement of $1 (`date`)"
	plot "<awk '/TRRESI/{print \$NF}' $1" title "R"
eof-cat2
fi

gnuplot gnuplot.inp
rm gnuplot.inp
