#!/usr/bin/python
import sys
import os
import subprocess
import re
def fatopdb(struct, pdbf):
	fo = open(pdbf, 'r')
	fw = open('newpdb', 'w')
	lines = fo.readlines()
	cc = 0;
	#for x in struct:
	fw.write(lines[0])
	for line in lines:
		try:
			if (struct[cc]+1) < int(line[22:25]):
				cc += 1
		
			if cc == len(struct):
				fw.write(lines[-1])
				return
		
			if (struct[cc]+1) == int(line[22:25]):
				fw.write(line)
		except ValueError:
			a = 0
		
	fw.write(lines[-1])
	return

if len(sys.argv) < 1:
	print 'Use ./pdb_to_dssp dssp_file'
	print "output is file dssp.new"
	exit()

dssp_lines = ''; fa_lines = ''
fdssp = open(sys.argv[1], 'r')
lines = fdssp.readlines()

for x in lines:
	dssp_lines += x.rstrip('\n')

pdbf = "../11czd_C_1t6l_A_dali.pdb"
os.system('./pdb2f '+pdbf)
fa = open('fa', 'r')
run = True

while(run):
	line = fa.readline()
	if not line: run = False
	fa_lines += line.rstrip('\n')

fa = 0; ds = 0; run = True; stuck = 0;
struct = []

while run:
	
	if dssp_lines[ds] == '-':
		ds += 1
		stuck = 0

	elif fa_lines[fa] == dssp_lines[ds]:
		struct.append(fa)
		fa += 1; ds += 1
		stuck = 0

	elif stuck > 15:
		ds += 1; fa -= 16		
		stuck = 0
	
	elif (ds < len(dssp_lines)-2 or fa < len(fa_lines)-2) and fa_lines[fa+1] == dssp_lines[ds+1] and fa_lines[fa+2] == dssp_lines[ds+2]:
			fa += 1; ds += 1

	else:
		stuck += 1
		fa += 1	

	if ds == len(dssp_lines) or fa == len(fa_lines): 
		run = False

fatopdb(struct, pdbf)
