#!/usr/bin/python
import re
import os, sys
def downloadNget(file_name, name):
	os.system('curl -s http://www.rcsb.org/pdb/explore/explore.do?structureId='+name+' > '+file_name)
	f = open(file_name, 'r')
	run = True
	Molecules = []
	while(run):
		line = f.readline()
		if re.match('.*se_xrayResolution.*', line):
			line = f.readline().rstrip('\n')
			Resolution = float(line) 
 		
		if re.match('.*>Molecule:</span>', line):
			f.readline(); tmp = f.readline().strip()

		if re.match('.*>Type:</span>', line):
			line = f.readline().rstrip('\n')
			if re.match('.*protein.*', line):
				Molecules.append(tmp)
			
		if not line: run = False

	return Resolution, Molecules

#downloadNget('get_structure', '3bep');
fg = open('groups_names', 'r')
fglines =  fg.readlines()
fw = open('Protein_molecule_res', 'w')
fogR = open("All_Proteins_Molecules_resolutions", 'w')
Molecules = {}
found_proteins = []

for fgline in fglines:
	fgline = fgline.rstrip('\n')
	group_file = open(fgline, 'r')
	group_lines = group_file.readlines()
	fogR.write('\n' + fgline[7:] + '\n')

	for line in group_lines:
		line = line.split()[1]
		if line[:4] not in found_proteins:
			found_proteins.append(line[:4])
			FPS, Mol= downloadNget('get_structure', line[:4])
			print line[:4], FPS
			for x in Mol:
				fogR.write(line[:4] + ' ' + x + ' ' + str(FPS) + '\n')
				if x in Molecules.keys():
					if FPS < Molecules[x][2]:
						Molecules[x] = (fgline[7:], line[:4], FPS)
				else:
					Molecules[x] = [fgline[7:], line[:4], FPS]

fw.write('Group          Protein  Molecule                                Resoluton\n')
for k,v in Molecules.iteritems():
	fw.write(v[0] + ' '*(15-len(v[0])) + v[1] + ' '*5 + k + ' '*(43-len(k)) + str(v[2]) + '\n')
