#! /bin/sh
FILES=''
count='ls -1 outputs/*.out | wc -l'
if [ count = 0 ]
then
    echo "doesn't exist"
fi

SACRIFICE=${1##*/}
CHECK=${SACRIFICE%.*}

if [ $CHECK = $1 ]
then
	echo "Skaitomas STDIN"
	#read seka
	seka='echo $2'
	echo $1 | diff - $2
	exit
fi

while [ $# -gt 0 ]
do
	case "$1" in
  	*) FILES="$FILES $1" ;;
        esac
        shift
done

for FILE in ${FILES}
do
	SACRIFICE=${FILE##*/}
	filename=inputs/${SACRIFICE%.*}.in
	echo $FILE $filename
	./ciftofasta ${filename} | diff - ${FILE} 
done
