#!/bin/sh
R --save <<EOF
	x11()
	Cifs_info <- read.table("inputs/CifsVdW_original", header=TRUE)
	attach(Cifs_info)
	jpeg("distBox")
	boxplot(distance~vdw)
	dev.off()	
	jpeg("Hist_vdw_dist")
	hist(dist_vdw_diff)
	dev.off()
EOF
