#!/usr/bin/Rscript
args <- commandArgs(trailingOnly = TRUE);
Mol <- read.table(args[1], sep = " ", header = TRUE);
plot(Mol$koord1, Mol$speed1, type='o', pch=15, col='blue',
        xlim=c(-1, 1), ylim = c(-10, 10), xlab="koord",ylab="speed", col.lab="green",
        cex = .6)
plot(Mol$koord2, Mol$speed2, type='o', pch=18, col='red', xlim=c(-1, 1), ylim = c(-100, 100))
plot(Mol$koord3, Mol$speed3, type='o', pch=18, col='yellow', xlim=c(-1, 1), ylim = c(-100, 100))
#lines(Mol$koord1, Mol$speed1, type='o', pch=16, col = 'red')
title(main="Molekuliu judejimas", col.main="red", font.main=4)
