#!/usr/bin/python
import sys
max_iv = {} 
for x in sys.argv[1:]:
	with open(x, 'r') as f:
		max_iv[x] = []
		mline = ""
		for line in f:
			if line.startswith("==="):
				line = line.rstrip("\n")
				#print line
				mline = line
			elif line.startswith("Correlation"):
				#print line.rstrip("\n")
				maxas = line.split()[2]
				max_iv[x].append((mline, maxas))

mline = (max_iv.keys()[0], max_iv[max_iv.keys()[0]][0][0])					
maxas = max_iv[max_iv.keys()[0]][0][1]
for k, values in max_iv.iteritems():
	for v in values:
		if float(v[1]) > float(maxas):
			mline = (k, v)
			maxas = v[1]

print mline
print maxas
