#!/usr/bin/python
import re
import os, sys
import fileinput

def file_len(fname):
        cc = 0
        with open(fname) as f:
                for i, l in enumerate(f):
                        if not l.strip():
                                cc += 1
                        pass
        return cc

def one_chain(input_chains):
	in_chains = input_chains.split()
        for chain in input_chains:
		linescc = 0
		with open("../"+chain+".pdb", 'r'):
			crline = cr.readline()
			if not crline: break
			if re.match(
	


def downloadNget(file_name, name):
	os.system('curl -s http://www.rcsb.org/pdb/explore/explore.do?structureId='+name+' > '+file_name)
	f = open(file_name, 'r')
	run = True
	Molecules = []
	Polymer_chains = {}
	polymer_cc = 0
	while(run):
		line = f.readline()
		if re.match('.*Polymer:</span></td>', line):
			polymer_cc += 1
		
		if re.match('.*Chains:</span></td>', line):
			line = f.readline().rstrip('\n')
			Chains = line[35:].split('>')[0].split('<')[0]
			Polymer_chains[polymer_cc] = Chains.split(',')

		if re.match('.*se_xrayResolution.*', line):
			line = f.readline().rstrip('\n')
			Resolution = float(line) 
 		
		if re.match('.*>Molecule:</span>', line):
			f.readline(); tmp = f.readline().strip()

		if re.match('.*>Type:</span>', line):
			line = f.readline().rstrip('\n')
			if re.match('.*protein.*', line):
				Molecules.append(tmp)
			
		if not line: run = False

	return Resolution, Molecules, Polymer_chains

#downloadNget('get_structure', '3bep');
try:
	fg = open(sys.argv[1], 'r')
except IndexError:
	print "Input groups names"
	sys.exit(1)

fglines =  fg.readlines()
fw = open('../outputs/Protein_molecule_res', 'w')
fogR = open("../outputs/All_Proteins_Molecules_resolutions", 'w')
Molecules = {}
found_proteins = []

for fgline in fglines:
	fgline = fgline.rstrip('\n')
	group_file = open("../"+fgline, 'r')
	group_lines = group_file.readlines()
	fogR.write('\n' + fgline[7:] + '\n')
	
	for line in group_lines:
		line = line.split()[1]
		if line[:4] not in found_proteins:
			found_proteins.append(line[:4])
			FPS, Mol, Poli_chains= downloadNget('get_structure', line[:4])
			print line[:4], FPS
			for i, (k,v) in enumerate(Poli_chains.iteritems()):
				myin = ''
				for x in v:
					x = x.replace(' ', '')
					print x
					myin += 'pdbs/'+line[:4]+'_'+x+' '
					print myin
				Chosen_one = one_chain(myin)
				print Chosen_one
			sys.exit(1)
			for x in Mol:
				fogR.write(x+' ' + line[:4] + ' ' + str(FPS) + '\n')
				if x in Molecules.keys():
					if FPS < Molecules[x][2]:
						Molecules[x] = (fgline[7:], line[:4], FPS)
				else:
					Molecules[x] = [fgline[7:], line[:4], FPS]

'''fw.write('Group          Protein  Molecule                                Resoluton\n')
for k,v in Molecules.iteritems():
'''#	fw.write(v[1] + ' ' + v[0] + ' '*(15-len(v[0])) +' '*5 + k + ' '*(43-len(k)) + str(v[2]) + '\n')
