#!/usr/bin/python
import re
import os, sys
import fileinput

def file_len(fname):
        cc = 0
        with open(fname) as f:
                for x in f:
			cc += 1
        return cc

def fullest_chain(input_chains):
	in_chains = input_chains.split()
	full_ch = ('chain', 0)
        for chain in in_chains:
		print chain
		chain_sz = file_len("../pdbs_sep/"+chain)
		if chain_sz > full_ch[1]:
			full_ch = (chain[5:], chain_sz)
	return full_ch[0]


def downloadNget(file_name, name):
	try:
		open(file_name)
	except IOError:
		print "Downloading:", name
		os.system('curl -s http://www.rcsb.org/pdb/explore/explore.do?structureId='+name+' > '+file_name)
	
	f = open(file_name, 'r')
	run = True
	Mol_Ch = {}
	Its_protein = 0
	Organizm = "";
	temp = []
	while(run):
		line = f.readline()
		if re.match(".*pdb:sentencePlus.*", line):
			Organizm = line.split('>')[1].split('<')[0]		
		elif re.match('.*>Molecule:</span>', line):
                        f.readline(); Mol = f.readline().strip()
                elif re.match('.*>Type:</span>', line):
                        Its_protein = 0
                        line = f.readline().rstrip('\n')
                        if re.match('.*protein.*', line):
				Its_protein = 1
				if Mol not in Mol_Ch.keys():
					Mol_Ch[Mol] = []
				else:
					print Mol, "jau aptikta"

		elif re.match('.*Chains:</span></td>', line) and Its_protein:
			temp = []
			line = f.readline().rstrip('\n')
			Chains = line[35:].split('>')[0].split('<')[0].split(',')
			for c in Chains:
				temp.append(c.strip())
			Mol_Ch[Mol] = temp

		if not line: run = False

	return Organizm, Mol_Ch;

#downloadNget('get_structure', '3bep');
try:
	fg = open(sys.argv[1], 'r')
except IndexError:
	print "Input groups names"
	sys.exit(1)

fglines =  fg.readlines()
fw = open('../outputs/Protein_molecule_res', 'w')
fogR = open("../outputs/All_Proteins_Molecules_resolutions", 'w')
found_proteins = []
Organism_mol = {}
all_molecule = []

for fgline in fglines:
	fgline = fgline.rstrip('\n')
	group_file = open("../"+fgline, 'r')
	group_lines = group_file.readlines()
	fogR.write('\n' + fgline[7:] + '\n')
	
	for line in group_lines:
		line = line.split()[1]
		if line[:4] not in found_proteins:
			found_proteins.append(line[:4])
			Org, Mol_Ch = downloadNget("../pdb_refs/" + line[:4], line[:4])
			if(Org not in Organism_mol.keys()):
				Organism_mol[Org] = []

			for m, chains in Mol_Ch.iteritems():
				for c in chains:
					Organism_mol[Org].append(line[:4] + '_' + c + ' ' + m)

			

for org, mol in Organism_mol.iteritems():
	fw.write(org+":\n")
	for m in mol:
		fw.write(str(m) + "\n")
	fw.write("\n");
