#!/usr/bin/python
import sys

def change_val(input_name):
	attr_list = []
	data_lines = []
	other_lines = []
	fC = open(input_name.split('.arff')[0] + "_Changed.arff", 'w')
	start_cc = 0
	
	with open(input_name, 'r') as f:
		for line in f:
			if(start_cc):
				data_lines.append(line)
				data = line.split(',')
				for i, x in enumerate(data):
					if(x != '?'):
						attr_list[i] = (float(attr_list[i][0]) + float(x), int(attr_list[i][1]) + 1)
			else:	
				fC.write(line)
			
			if(line.startswith("@attribute")):
                                attr_name = line.split()[1]
                                attr_list.append((0.0, 0))
			elif(line.startswith("@data")):
                                start_cc = 1

	for i, x in enumerate(attr_list):
		attr_list[i] = round(x[0]/x[1], 2)

	for x in data_lines:
		splix = x.split(',')
		length = len(splix) - 1
		for i, y in enumerate(splix):
			if(y == '?'):
				y = attr_list[i]
			
			if(i != length):
				fC.write(str(float(y)) + ',')
			else:
				fC.write(str(float(y)) + "\n")

def remove_val(input_name):
	
	fR = open(input_name.split('.arff')[0] + "_Removed.arff", 'w')
	with open(input_name, 'r') as f:
		for line in f:
			line = line.rstrip("\n")
			splitted = line.split(',')
			isSymbol = 0
			appline = ""
			for x in splitted:
				if(x == '?'):
					isSymbol = 1

			if(not isSymbol):
				fR.write(line + "\n")

	fR.close()
						
try:
	sys.argv[1]
except IndexError:
	print "input arff file with ? values"
	sys.exit(1)

change_val(sys.argv[1])
remove_val(sys.argv[1])
